[package]
org = "ballerinax"
name = "asb"
version = "2.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Message Brokers", "Cost/Paid", "Vendor/Microsoft"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-service-bus"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../asb-native/build/libs/asb-native-2.0.0-all.jar"
groupId = "org.ballerinax"
artifactId = "asb-native"
module = "asb-native" 
version = "2.0.0"
