[package]
distribution = "2201.3.1"
org = "ballerinax"
name = "asb"
version = "3.0.3"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Message Brokers", "Cost/Paid", "Vendor/Microsoft"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-azure-service-bus"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
path = "../asb-native/build/libs/asb-native-3.0.3.jar"
groupId = "org.ballerinax"
artifactId = "asb-native"
module = "asb-native" 
version = "3.0.3"

