name: PR Build

on: [ pull_request ]

jobs:
  ubuntu-build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
          JAVA_OPTS: -DBALLERINA_DEV_COMPILE_BALLERINA_ORG=true
        run: ./gradlew build --scan --no-daemon
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1
        with:
          version: 2201.3.1
      - name: Ballerina Build
        run: bal build ./ballerina

  windows-build:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
          JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
        run: ./gradlew.bat build --scan --no-daemon
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1
        with:
          version: 2201.3.1
      - name: Ballerina Build
        run: bal build ./ballerina

  ballerina-tests:
    name: Run Ballerina Tests
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1
        with:
          version: 2201.6.0
      - name: Ballerina Test
        run: bal test ./ballerina
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          QUEUE_NAME: ${{ secrets.QUEUE_NAME }}
          TOPIC_NAME: ${{ secrets.TOPIC_NAME }}
          SUBSCRIPTION_NAME1: ${{ secrets.SUBSCRIPTION_NAME1 }}
          SUBSCRIPTION_NAME2: ${{ secrets.SUBSCRIPTION_NAME2 }}
          SUBSCRIPTION_NAME3: ${{ secrets.SUBSCRIPTION_NAME3 }}
